update merge module to latest.
tamakon/junk-t pull request #69
Opened 2018-11-11 10:35 UTC by tronperidot

```
We found a potential security vulnerability in one of your dependencies.
```

Security alert by github.
Instruction of update the merge module to  latest.

Together we did `ncu -u`

2018-11-11 13:37 UTC, h-haraguchi requested changes
merge モジュール変わってないっぽいべ

2018-11-11 13:40 UTC, h-haraguchi commented on client/yarn.lock
>  merge@^1.2.0:
ここかな

2018-11-11 13:42 UTC, h-haraguchi approved these changes

2018-11-11 13:42 UTC, h-haraguchi commented on client/package-lock.json
> +      "version": "1.2.1",
package-lock.jsonのほうはかわってるから、これでいいのかな。

2018-11-11 13:45 UTC, tronperidot commented on client/package-lock.json
> +      "version": "1.2.1",
そゆことだね

2018-11-15 02:43 UTC, takashi1coq approved these changes

2018-11-15 11:48 UTC, merged